### ISSUE TITLE
Not able to "make"

### ISSUE THREAD

**Issue by vervenumen** [johnwbyrd/logog#37]
Following were the output of "cmake" command:
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Desktop/logog-master/build

After that, following were the output of "make" command in the build folder:
Scanning dependencies of target logog
[  6%] Building CXX object CMakeFiles/logog.dir/src/api.cpp.o
[ 12%] Building CXX object CMakeFiles/logog.dir/src/checkpoint.cpp.o
[ 18%] Building CXX object CMakeFiles/logog.dir/src/formatter.cpp.o
[ 25%] Building CXX object CMakeFiles/logog.dir/src/lobject.cpp.o
[ 31%] Building CXX object CMakeFiles/logog.dir/src/lstring.cpp.o
[ 37%] Building CXX object CMakeFiles/logog.dir/src/message.cpp.o
[ 43%] Building CXX object CMakeFiles/logog.dir/src/mutex.cpp.o
[ 50%] Building CXX object CMakeFiles/logog.dir/src/node.cpp.o
[ 56%] Building CXX object CMakeFiles/logog.dir/src/platform.cpp.o
[ 62%] Building CXX object CMakeFiles/logog.dir/src/socket.cpp.o
[ 68%] Building CXX object CMakeFiles/logog.dir/src/statics.cpp.o
[ 75%] Building CXX object CMakeFiles/logog.dir/src/target.cpp.o
[ 81%] Building CXX object CMakeFiles/logog.dir/src/timer.cpp.o
[ 87%] Building CXX object CMakeFiles/logog.dir/src/topic.cpp.o
[ 93%] Building CXX object CMakeFiles/logog.dir/src/unittest.cpp.o
Linking CXX static library liblogog.a
[ 93%] Built target logog
Scanning dependencies of target test-logog
[100%] Building CXX object CMakeFiles/test-logog.dir/test/test.cpp.o
Linking CXX executable test-logog
CMakeFiles/test-logog.dir/test/test.cpp.o: In function `logog::Thread::Start()':
test.cpp:(.text._ZN5logog6Thread5StartEv[_ZN5logog6Thread5StartEv]+0x29): undefined reference to `pthread_create'
CMakeFiles/test-logog.dir/test/test.cpp.o: In function `logog::Thread::WaitFor(logog::Thread const&)':
test.cpp:(.text._ZN5logog6Thread7WaitForERKS0_[_ZN5logog6Thread7WaitForERKS0_]+0x1c): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[2]: *** [test-logog] Error 1
make[1]: *** [CMakeFiles/test-logog.dir/all] Error 2
make: *** [all] Error 2

Any ideas why this might be happening?

**Comment by johnwbyrd** [comment]
It seems that your compilation environment is complaining about a lack of
pthread_create and pthread_join on your platform. That is odd, because
cmake thinks it's found a pthread header file. What platform are you
targeting?

**Comment by vervenumen** [comment]
Following are the output of:
cat /etc/lsb-release 
>>DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

**Comment by johnwbyrd** [comment]
I clean installed Ubuntu 14.04.3 LTS onto a virtual machine with default settings (desktop installation, x64 mode install) and logog installed and ran its test suite without complaint.

It seems to me that the detection step of pthreads on your machine differs from the stock Ubuntu 14.04.3 installation for some reason.  As you can see below, my installation detects pthread headers at a different place from yours.  I suspect you may have installed competing versions of pthreads on your particular machine, but I am not sure.

Below is the typescript of the conversation I had with Ubuntu 14.04.3 LTS.  I hope it helps you find the particular misbehavior on your machine.  You are not required to use cmake to compile logog, but if you choose to compile yourself, you must manage the correct pthreads headers and library dependencies yourself.  In extremis you may consider reinstalling a clean build of 14.04.3 and working from there.

---

 # sudo apt-get install git build-essential cmake
 # git clone http://github.com/johnwbyrd/logog.git 
 # cd logog 
 # mkdir build
 # cd build
 # cmake ..

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jbyrd/logog/build

 # make

Scanning dependencies of target logog
Building CXX object CMakeFiles/logog.dir/src/api.cpp.o
Building CXX object CMakeFiles/logog.dir/src/checkpoint.cpp.o
Building CXX object CMakeFiles/logog.dir/src/formatter.cpp.o
Building CXX object CMakeFiles/logog.dir/src/lobject.cpp.o
Building CXX object CMakeFiles/logog.dir/src/lstring.cpp.o
Building CXX object CMakeFiles/logog.dir/src/message.cpp.o
Building CXX object CMakeFiles/logog.dir/src/mutex.cpp.o
Building CXX object CMakeFiles/logog.dir/src/node.cpp.o
Building CXX object CMakeFiles/logog.dir/src/platform.cpp.o
Building CXX object CMakeFiles/logog.dir/src/socket.cpp.o
Building CXX object CMakeFiles/logog.dir/src/statics.cpp.o
Building CXX object CMakeFiles/logog.dir/src/target.cpp.o
Building CXX object CMakeFiles/logog.dir/src/timer.cpp.o
Building CXX object CMakeFiles/logog.dir/src/topic.cpp.o
Building CXX object CMakeFiles/logog.dir/src/unittest.cpp.o
Linking CXX static library liblogog.a
Built target logog

Scanning dependencies of target test-logog
Building CXX object CMakeFiles/test-logog.dir/test/test.cpp.o
Linking CXX executable test-logog
Built target test-logog

 # ./test-logog 

[... snip ...]
Testing complete, 25 total tests, 25 tests succeeded, 0 failed
