### ISSUE TITLE
Warning	C26495 Variable 'logog::Thread::m_Thread' is uninitialized. Always initialize a member variable (type.6).	At: thread.hpp	78	

### ISSUE THREAD

**Issue by rbento** [johnwbyrd/logog#41]
Following the documentation. 

My project compiles and links properly.

In my code:

	LOGOG_INITIALIZE();

	INFO("Core::initialize");

At runtime I get the following warning:

Warning	C26495 Variable 'logog::Thread::m_Thread' is uninitialized. Always initialize a member variable (type.6).	

At: thread.hpp	78

Just reporting so it can be fixed at some point.

Thank you.

**Comment by rbento** [comment]
Hi John, just submitted a PR with the fix.

Thank you!

**Comment by johnwbyrd** [comment]
PR accepted.
